# Generated by Django 3.1.7 on 2021-03-07 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marathons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.TextField(null=True)),
                ('image', models.ImageField(default='def_img_for_articles.jpg', upload_to='static/doctor')),
                ('starting_day', models.DateField()),
                ('ending_day', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('results', models.TextField(default='Not finished!')),
            ],
        ),
    ]
